### ISSUE TITLE
typo in infrastructure/request_dict.py?

### ISSUE THREAD

**Issue by SpeedCoder5** [talkpython/htmx-python-course#4]
Lines 24-26 of https://github.com/talkpython/htmx-python-course/blob/main/code/ch4_app/ch4_starter_video_collector/infrastructure/request_dict.py read:

    form = request.form
    if isinstance(request.args, MultiDict):
        form = request.form.to_dict()

Should request.args in line 25 be changed to request.form so it reads:

    form = request.form
    if isinstance(request.form, MultiDict):
        form = request.form.to_dict()

?

**Comment by mikeckennedy** [comment]
You're right, that was a mistake. I just fixed it. Thank you!
